<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Point Flow Documentation</title>

    <script type="module">
        import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
        mermaid.initialize({ startOnLoad: true });
    </script>

    <style>
        body {
            font-family: Arial, sans-serif;
            padding: 40px;
            line-height: 1.6;
            max-width: 1200px;
            margin: auto;
        }

        h1,
        h2,
        h3 {
            color: #333;
        }

        pre {
            background: #f4f4f4;
            padding: 10px;
            overflow-x: auto;
        }

        .mermaid {
            background: white;
            padding: 20px;
            border: 1px solid #ddd;
            margin-top: 20px;
            margin-bottom: 20px;
        }
    </style>
</head>

<body>

    <h1>Point Flow System Documentation</h1>

    <h2>1. Initial Point Generation</h2>

    <p>
        Points can be generated by Admin or authorized users.
    </p>

    <div class="mermaid">
        flowchart TD

        A[Admin or Authorized User]
        --> B[Call creditPoints API]

        B --> C[Generate Branch Point]

        C --> D[Insert Into cdt_pnt Table]

        D --> E[Update Branch Balance]
    </div>

    <h3>Endpoint</h3>

    <pre>
POST /points/creditPoints
    </pre>

    <h3>Request</h3>

    <pre>
{
  "divCode": "B1",
  "giverID": "admin",
  "point": 10000
}
    </pre>

    <hr>

    <h2>2. Branch To Driver Point Transfer</h2>

    <div class="mermaid">
        flowchart TD

        A[Branch Manager]
        --> B[Call givePoints API]

        B --> C{Enough Branch Point}

        C -->|Yes| D[Transfer Point To Driver]

        D --> E[Insert giv_pnt]

        E --> F[Deduct branch_info]

        F --> G[Add driver_point]

        G --> H[Insert driver_point_record]

        H --> I[Success Response]

        C -->|No| J[Insufficient Point Error]
    </div>

    <h3>Endpoint</h3>

    <pre>
POST /points/givePoints
    </pre>

    <hr>

    <h2>3. Driver Withdrawal Request</h2>

    <div class="mermaid">
        flowchart TD

        A[Driver]
        --> B[Call withdrawPointsRequest API]

        B --> C{Monthly Limit Exceeded}

        C -->|No| D[Insert req_pnt]

        D --> E[Create Withdrawal Request]

        E --> F[Success Response]

        C -->|Yes| G[Return Error]
    </div>

    <hr>

    <h2>4. Cancel Withdrawal Request</h2>

    <div class="mermaid">
        flowchart TD

        A[Driver]
        --> B[Call cancelWithdrawalRequest API]

        B --> C[Cancel Withdrawal Request]

        C --> D[Update Request Status]
    </div>

    <hr>

    <h2>5. Branch Manager Response</h2>

    <div class="mermaid">
        flowchart TD

        A[Branch Manager]
        --> B[Call responseWithdrawRequest API]

        B --> C{modReqPoint Value}

        C -->|Equal| D[Fully Approved]

        C -->|Zero| E[Rejected]

        C -->|Partial| F[Partially Approved]

        D --> G[Update req_pnt]

        E --> G

        F --> G

        G --> H[Response Completed]
    </div>

    <hr>

    <h2>Complete Sequence Diagram</h2>

    <div class="mermaid">
        sequenceDiagram

        participant Admin
        participant BranchManager
        participant Driver
        participant System
        participant Database

        Admin->>System: creditPoints Request

        System->>Database: Insert cdt_pnt

        System-->>Admin: Success Response

        BranchManager->>System: givePoints Request

        System->>Database: Check Branch Balance

        alt Enough Point

        System->>Database: Insert giv_pnt

        System->>Database: Update branch_info

        System->>Database: Update driver_point

        System->>Database: Insert driver_point_record

        System-->>BranchManager: Success Response

        else Insufficient Point

        System-->>BranchManager: Error Response

        end

        Driver->>System: withdrawPointsRequest

        System->>Database: Insert req_pnt

        System-->>Driver: Withdrawal Request Created

        BranchManager->>System: responseWithdrawRequest

        System->>Database: Update req_pnt

        System-->>BranchManager: Response Completed
    </div>

</body>

</html>